#!/usr/bin/env bash

PYTHON="--enable-python3interp"

OPTS="--enable-rubyinterp=dynamic  \
      --enable-tclinterp \
      --enable-multibyte  \
      --enable-cscope"

DEBUG_FLAGS="-g -gdwarf-4 -DDEBUG -O0 -fno-omit-frame-pointer"
SANITIZER_FLAGS='-DABORT_ON_INTERNAL_ERROR -DEXITFREE'
LD=lld

BREW_PYTHON=1
PYTHON_TYPE=""
while [[ -n "$1" ]]; do
  OPT=$1
  shift
  case "$OPT" in
    "--debug")
      export CFLAGS="${CFLAGS} ${DEBUG_FLAGS}"
      ;;
    "--asan")
      export CFLAGS="${CFLAGS} ${DEBUG_FLAGS} ${SANITIZER_FLAGS} -fsanitize=address"
      export LIBS="${DEBUG_FLAGS} ${SANITIZER_FLAGS} -fsanitize=address"
      ;;
    "--ubsan")
      export CFLAGS="${CFLAGS} ${DEBUG_FLAGS} -${SANITIZER_FLAGS} fsanitize=undefined"
      export LIBS="${DEBUG_FLAGS} ${SANITIZER_FLAGS} -fsanitize=undefined"
      ;;
    "--no-brew-python")
      BREW_PYTHON=0
      ;;
    "--debug-python")
      export CFLAGS="${CFLAGS} -DPy_DEBUG -DPy_DEBUG_NO_PYMALLOC"
      BREW_PYTHON=0
      OPTS="--enable-python3interp"
      ;;
    "--python2")
      PYTHON="--enable-pythoninterp"
      ;;
    "--python3")
      PYTHON="--enable-python3interp"
      ;;
    "--python2-python3")
      PYTHON="--enable-pythoninterp --enable-python3interp"
      ;;
    "--python-type")
      PYTHON_TYPE="=$1"
      shift
      ;;
    "--no-python")
      PYTHON=""
      ;;
    "--")
      break
      ;;
    *)
      echo "Unknown option $OPT"
      exit 1
      ;;
  esac
done

echo "Additional args: "$@""

if [[ $BREW_PYTHON == 1 ]]; then
  echo "Using homebrew python"
  export PATH=$(brew --prefix python)/bin:${PATH}
fi

make distclean
./configure --prefix=/Users/ben/Development/vim-env \
            --with-features=huge \
            --enable-terminal \
            ${PYTHON}${PYTHON_TYPE} \
            ${OPTS} \
            --enable-fail-if-missing \
            "$@"
